stages:
  - build

build:
  stage: build
  script:
    - git submodule sync
    - git submodule update --init
    - arduino --pref build.path=./build --board esp8266:esp8266:d1_mini_lite:CpuFrequency=80,FlashSize=1M0 --verify ./esp8266-garage.ino --save-prefs
    - espota.py -d -i 192.168.3.100 -f ./build/esp8266-garage.ino.bin
